### ISSUE TITLE
Support Bulma v0.9

### ISSUE THREAD

**Issue by MarkGriffiths** [wtho/bulma-css-vars#13]
Following Buefy's recent update I was following the docs as I _really_ could use smarter css variable colour handling for dynamic themes and started hitting this...

```
(node:10019) UnhandledPromiseRejectionWarning: Error: Can't find stylesheet to import.
  ╷
4 │ @import "../bulma/sass/utilities/derived-variables.sass"
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/bulma-css-vars/bulma-cv-utilities.sass 4:9  @import
  node_modules/bulma-css-vars/bulma-cv-lib.sass 3:9        @import
  src/main.scss 3:9                                        root stylesheet
```

Tracing it through, `bulma-cv-utilities.sass` has `@import "../bulma/sass/utilities/derived-variables.sass"` but it seems that files has become SCSS `../bulma/sass/utilities/derived-variables.scss`

Buefy's new docs suggest Bulma 0.8 'or higher' - I guess I need to pin it to ~0.8.0?

**Comment by wtho** [comment]
Yeah, Bulma v0.9 is a breaking version, I have to make some adjustments to this library.
Until then, pin it to 0.8 using e. g. `^0.8` or `~0.8`.

**Comment by wtho** [comment]
Should work in v0.4.5
