### ISSUE TITLE
Error: [Bulma CSS Vars] cannot create definitions, entry sass file does not exist in file system

### ISSUE THREAD

**Issue by Aeox85** [wtho/bulma-css-vars#19]
Hi,

When i try to run "bulma-css-vars" locally (windows 10) i'm getting the following message:

`(node:112956) UnhandledPromiseRejectionWarning: Error: [Bulma CSS Vars] cannot create definitions, entry sass file does not exist in file system at <blanked>\src\main.scss
    at <blanked>\node_modules\bulma-css-vars\dist\cli.js:58:19
    at Generator.next (<anonymous>)
    at fulfilled (<blanked>\node_modules\bulma-css-vars\dist\cli.js:5:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
(node:112956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:112956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

However, the file absolutely exists in that location and consists of:

@import './bulma/generated-fallback.css'; // import fallbacks first, so they are overridden
@import './bulma/generated-vars.sass';
@import '../node_modules/bulma-css-vars/bulma-cv-lib';

bulma-css-vars.config.js has the following (excluding colour settings): 

module.exports = {
  sassEntryFile: './src/main.scss',
  jsOutputFile: './src/bulma/bulma-colors.js',
  sassOutputFile: './src/bulma/generated-vars.sass',
  cssFallbackOutputFile: './src/bulma/generated-fallbacks.css',
  colorDefs: appColors,
  globalWebVar: false,
  transition: '0.5s ease',
}

**Comment by Aeox85** [comment]
Turns out i needed to update node!

**Comment by acarpe13** [comment]
@Aeox85 What version of node were you using and what version fixed it? I'm experiencing something similar right now

**Comment by Aeox85** [comment]
@acarpe13 v12.18.3 is what i'm running now. I can't remember the exact version i was using before but it was v10.something.

Also, something else i found was causing an issue, just in case you have something similar.

When you go to initiate bulma-css-vars, place it in your package.json without "node". So for example:
"scripts": {
"init-bulma-colors" : "./node_modules/.bin/bulma-css-vars --init"
}

instead of:

"init-bulma-colors" : "node ./node_modules/.bin/bulma-css-vars --init"

**Comment by acarpe13** [comment]
@Aeox85 
Strange, I'm on 14.9 and I get that same error.

Maybe I'm misunderstanding something about the implementation but I thought --init was only to generate the config file the first time and the script in package.json is instead supposed to regenerate the Bulma generated files. 

When I read the directions here: https://buefy.org/extensions/bulmacssvars
they said to add this to your package.json:
`"scripts": {
  "bulma-css-vars": "bulma-css-vars"
}`

When I run 'npm run bulma-css-vars' I get that error you listed above even though my config file is exactly where it is looking.
Are you able to change one of the colors in your config and it regenerate correctly?

**Comment by Aeox85** [comment]
I managed to get it working after upgrading and running the init. Before i upgraded i had trouble with the init saying that there was a missing } in one of the files because i was using:

`"init-bulma-colors" : "node ./node_modules/.bin/bulma-css-vars --init"`

After it created the config and the bulma generated files, it seemed to work after pulling my hair out.

My setup which works is:

bulma-css-vars.config:

```
const { rgb } = require('bulma-css-vars')

const appColors = {
  "primary": '#73a56e',
}

module.exports = {
  sassEntryFile: 'src/main.scss',
  jsOutputFile: 'src/bulma-generated/bulma-colors.js',
  sassOutputFile: 'src/bulma-generated/generated-bulma-vars.sass',
  cssFallbackOutputFile: 'src/bulma-generated/generated-fallback.css',
  colorDefs: appColors,
  globalWebVar: false,
  transition: '0.5s ease'
}
```

main.scss:

`@import "assets/scss/components/example";`

example.scss:

```
.test_container {
background-color: var(--primary);
}
```

I think have a main scss file which pulls the generated scss files + my example:

app_main.scss:

```
@import 'bulma-generated/generated-fallback.css';
@import 'bulma-generated/generated-bulma-vars.sass';
@import "assets/scss/components/example";
```

Just for completion, my generated-fallback.css, generated-bulma-vars and bulma-colors.js files look like below:

bulma-colors.js:

```
module.exports = {
  "bulmaCssVariablesDefs": {
    "primary": {
      "calls": []
    }
  }
}
```

generated-bulma-vars.scss:


```
// sass variables
$primary: var(--primary)

// declared base css variables
#{":root"}
  --primary: rgb(115, 165, 110)

// derived, generated css variables
#{":root"}

```

Hopefully you can get it working off the back of that. I can change a colour in 'bulma-css-vars.config' and then rerun the 'bulma-css-vars' script and it works just fine.

One thing to note is that it doesn't work if you have numbers in your colour variables (e.g. var(--test_container_2)). I also can't find a way for it to use alpha. So everything comes out as a solid colour.

**Comment by acarpe13** [comment]
Thank you so much for all the detail, hopefully I'll be able to get it running soon!

**Comment by acarpe13** [comment]
@Aeox85 Thank you so much for all the detail, hopefully I'll be able to get it running soon!

**Comment by Aeox85** [comment]
@acarpe13 No probs. Fingers crossed my dude!
