### ISSUE TITLE
Create a new bulma fork

### ISSUE THREAD

**Issue by stafyniaksacha** [wtho/bulma-css-vars#200]
Hello there! 

We love using Bulma at cssninjaStudio, but we think the release process does not fit the new modern way that we should follow.
Your package introduced a huge feature that we want to go through (switching to native css vars)

Nowadays, we got awesome features from native CSS engines (css vars, css4, hsl calc, ....) and only windycss or tailwind are going (to me) in the good way.

The idea would be to create and maintain a new fork of  https://github.com/jgthms/bulma as a playground with new features.
We can then try those features and discuss them before getting into the official Bulma package.

We mainly want to go through these features:
- Use native css variables (hsl with calc instead of darken/lighten)
- Keep scss builder up to date but fast (knowing https://github.com/sass/dart-sass/issues/113)

The questions are:
- Is this effort is relevant with jit features introduced in windy / tailwind
- How can we benefit from compilation features of scss and still having fast dev experience and minimum/cleaver final bundle size

**Comment by driss-chelouati** [comment]
Hi, 
Iam also in line with what @stafyniaksacha said. We should definitely rewrite some of the Bulma package. I think that most of the time, we don't need most of the Bulma components. Therefore, there should be a way to modularize each component so we can only import what we need when we need it, the most important part being CSS vars and layout grid / helpers and responsiveness.

**Comment by wtho** [comment]
Hey!

I agree, Bulma has potential, but lacks modern standard css-framework features.

But I personally do currently not use bulma in any project and I will just put the effort to maintain this library, but not more.

Go through https://github.com/jgthms/bulma/issues/3074 and related issues if you want to stick to the plan of forking bulma.

@Tofandel at some point had a more coherent way of integrating css variables into bulma, you should look at [his PR](https://github.com/jgthms/bulma/pull/2981) on the bulma repo.

I will close this issue for now, as this is not related to this repository. `bulma-css-vars` just tries to add css variables to bulma only where required by interfering with the bulma code itself as little as possible. A fork and partial rewrite would not follow the goal.

If you think the issue should stay open, you can bring up new arguments, but as I said, I personally am not really interested in a bulma fork.

Cheers!
