### ISSUE TITLE
Is there a working example using Nuxt?

### ISSUE THREAD

**Issue by Macscroge** [wtho/bulma-css-vars#22]
I can get it working with Vue but under Nuxt I cannot get the sass loader to function. If anyone had a working example it would be very much appreciated.

**Comment by wtho** [comment]
If you use `@nuxtjs/bulma`, you will run into issues as long as the underlying package `nuxt-bulma-slim` does not support the dart sass compiler (aka `sass`).
I think it will be a small change to `@nuxtjs/bulma` to e. g. add an opt-in option to use the more modern dart-sass compiler. You could open an issue/PR over at [nuxt-bulma-slim](https://github.com/mustardamus/nuxt-bulma-slim).

Once this is merged I can help you to set up a working example with `bulma-css-vars`.

---

Optionally, you can set up a fully separate of the bulma sass compilation with variables, but I do not know if you can use sass in vue components in that case.

**Comment by wtho** [comment]
I had another try at it and made it work. The key is to not use `@nuxtjs/bulma`, but set it up on your own.

Have a look at [this example](https://github.com/wtho/nuxt-bulma-css-vars-example).

Cheers and happy coding!

**Comment by Macscroge** [comment]
Thank you so much !
