### ISSUE TITLE
JS error: ColorUpdater don't have a constructor

### ISSUE THREAD

**Issue by AcelisWeaven** [wtho/bulma-css-vars#3]
Hi @wtho, thanks for the project!

I've got some trouble installing it on my project (I use Symfony Encore) but I finally got it working.
However, I had to change the example because it complained that ColorUpdater didn't have a constructor. (the variable was undefined)

I had to change the code a little bit to get it working:
```js
import {ColorUpdater} from 'bulma-css-vars/dist/color-updater';
import bulmaCssVariablesDefs from './generated/bulma-colors';

const colorUpdater = new ColorUpdater(bulmaCssVariablesDefs);

colorUpdater.updateVarsInDocument(name, value);
```

Should I make a pull-request? I'm not sure that's the best way to do it.
(also, the JS example has minor typos, like : instead of ; so I'll probably make a request anyway 👍 )

**Comment by wtho** [comment]
Oh, you are right! When using javascript as output format, the import has to be direct (no destructuring)! 
Actually I would prefer to change that and make the generated file match the documentation, so `cli.ts` in the sources has to be adjusted.

And yeah, thank you for pointing out the issue with the `:`! Feel free to open a PR!

**Comment by AcelisWeaven** [comment]
Okay I'll do it! What about the require that had to be changed for the color updater? Can this also be fixed without changing the doc?

For the reference, here's the require syntax that works:
```js
const {ColorUpdater} = require("bulma-css-vars/dist/color-updater");
```

For the `:`, I'll make a PR right now, thanks!

**Comment by wtho** [comment]
I built-in the js file template right into the `cli.ts`, it might be better to reformat that later, but for now it should be ok.

Here you can see the template:
https://github.com/wtho/bulma-css-vars/blob/22c30c01c65ab3400673c838f1cfd95074caddd0/lib/src/cli.ts#L154-L156
It has to be extended to be a sub-property of the generated module, something like this:
```js
  jsOutputContent = ` 
module.exports = {
  bulmaCssVariablesDefs: ${JSON.stringify(usedVars, null, 2)} 
}
` 
```
Then a destructuring import accessing `bulmaCssVariablesDefs` should work again.

Sadly there are no tests yet for the generation, I want to separate the actual *write-to-FS* part from the app logic to make it easier testable, but that will be a task for a different PR.
